export const localPaths = {
  HOME: "/",
  ABOUT: "/about",
  SIGNIN: "/signIn",
  REGISTER: "/register",
  RECOMMENDATION: "/recommendation",
  SEARCH: "/search",
  // CATEGORIES: "/categories",
  MOVIES: "/movies",
  SERIES: "/series",
  // ANIMES: "/animes",
  MOVIE: "/movie",
  SERIE: "/serie",
  // ANIME: "/anime/:id",
};
